[workspace]
members = ["packages/evm-rpc-canister-types", "canisters/chain_fusion", "packages/ic-evm-utils"]
resolver = "2"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.14"
serde = "1.0.197"
serde_bytes = "0.11.14"
serde_json = "1.0.116"
